# Generated by Django 2.1.2 on 2018-10-24 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='userprofile/static/userprofile/files')),
                ('image', models.ImageField(upload_to='userprofile/static/userprofile/img')),
            ],
        ),
    ]
