# Generated by Django 2.1.2 on 2018-10-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='file',
            field=models.FileField(blank=True, upload_to='userprofile/static/userprofile/files'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='userprofile/static/userprofile/img'),
        ),
    ]
